### ISSUE TITLE
From angular to github.io

### ISSUE THREAD

**Issue by zzzdeb** [javkhaanj7/javkhaanj7.github.io#1]
Маш гоё хичээл байна. Ангулар орчиноос гитхаб дээр ажиллах вэб үүсгэсэн замаа дэлгэрүүлээч?

**Comment by javkhaanj7** [comment]
Баярлалаа. Хэрэв `package.json` файлыг нээж харсан бол тэнд production-д зориулж build хийх **ng build** комманд байрлаж байгаа. Ажиллуулснаар project дотор **dist** фолдер үүснэ.

Үүнийгээ `[username].github.io` дотор хуулж өгөөд боллоо. [Энд](https://pages.github.com/) дэлгэрэнгүй тайлбарласан байна.

Жич: [weather-mn](https://github.com/javkhaanj7/weather-mn)-г ямар нэгэн хувийн зорилгод /үйл ажиллагаанд/ ашиглах гэж байгаа бол энэхүү үндсэн эх source-оо дурьдахыг хүсэж байна (мөн ашиглагдсан зургууд).  :-)
